version: "3"

services:
    client:
        build: ./client
        container_name: Care-Connections-Client
        working_dir: /usr/src/app
        volumes:
            - ./client/:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - ${CLIENT_PORT}:3000
        command: yarn dev
        restart: always
        depends_on:
            - "mongodb"

    api:
        build: ./api
        container_name: Care-Connections-API
        working_dir: /usr/src/app
        volumes:
            - ./api/:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - ${API_PORT}:3000
        command: yarn dev
        restart: always
        depends_on:
            - "mongodb"

    mongodb:
        container_name: MongoDB
        image: mongo
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
            - MONGO_INITDB_DATABASE=${DATABASE_NAME}
        volumes:
            - D:\Projects\Programmas\CareKickoff\Data:/init/
            - D:\Projects\Programmas\CareKickoff\src\init.js:/docker-entrypoint-initdb.d/init.js:ro
            - database:/data/db
        command: [--auth]
        restart: always

    mongo-express:
        container_name: Mongo-Express
        image: mongo-express
        ports:
            - ${MONGO_EXPRESS_PORT}:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=admin
            - ME_CONFIG_MONGODB_SERVER=mongodb
        restart: always
        depends_on:
            - "mongodb"

volumes:
    database:
        driver: local
